spring:
  application:
    name: kommentar-service
server:
  port: 9021


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    register-with-eureka: true
    fetch-registry: true
